modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"

[[mods]]
modId="my_first_mod"
version="1.0"
displayName="My First Mod"
authors="by Grapo"
description='''
	This is my first mod.
'''

[[dependencies.examplemod]]    
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
